♻️ Refactorizar el comando de inicio de sesión en Docker Hub para mejorar la seguridad al ocultar la contraseña

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -27,8 +27,7 @@ jobs:
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: | 
           echo "Attempting to login to Docker Hub"
-          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
-
+          docker login -u $DOCKER_USER -p $(echo $DOCKER_PASSWORD) || echo "Login failed"
       - name: Build the Docker image
         env:
           VERSION: ${{ steps.version.outputs.version }}
